"use client";

import React from "react";
import { FilmComparisonResult } from "../../lib/ai/tools";
import { Scale, Sparkles, Trophy, Star } from "lucide-react";

interface FilmComparisonChartProps {
  data: FilmComparisonResult;
}

export function FilmComparisonChart({ data }: FilmComparisonChartProps) {
  const metrics = [
    { label: "Visual Spectacle", keyA: data.filmA.visualSpectacle, keyB: data.filmB.visualSpectacle },
    { label: "Narrative Complexity", keyA: data.filmA.narrativeComplexity, keyB: data.filmB.narrativeComplexity },
    { label: "Emotional Resonance", keyA: data.filmA.emotionalResonance, keyB: data.filmB.emotionalResonance },
    { label: "Pacing Speed", keyA: data.filmA.pacingSpeed, keyB: data.filmB.pacingSpeed },
  ];

  return (
    <div className="w-full my-4 rounded-2xl bg-zinc-950/90 border border-indigo-500/30 overflow-hidden shadow-xl shadow-black/40 text-zinc-200">
      {/* Header */}
      <div className="p-5 bg-gradient-to-r from-indigo-950/40 via-zinc-900/60 to-zinc-950 border-b border-zinc-800 flex items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="h-10 w-10 rounded-xl bg-indigo-600/20 border border-indigo-500/40 flex items-center justify-center text-indigo-400">
            <Scale className="h-5 w-5" />
          </div>
          <div>
            <h3 className="text-sm font-extrabold text-white flex items-center gap-2">
              Head-to-Head Film Comparison
            </h3>
            <p className="text-[11px] text-zinc-400">
              Comparative cinematic analysis generated by AI
            </p>
          </div>
        </div>

        {/* Legend */}
        <div className="flex items-center gap-4 text-xs font-semibold">
          <span className="flex items-center gap-1.5 text-violet-400">
            <span className="h-2 w-2 rounded-full bg-violet-500" />
            {data.filmA.title} ({data.filmA.year})
          </span>
          <span className="flex items-center gap-1.5 text-indigo-400">
            <span className="h-2 w-2 rounded-full bg-indigo-500" />
            {data.filmB.title} ({data.filmB.year})
          </span>
        </div>
      </div>

      {/* Comparative SVG / Bar Chart Area */}
      <div className="p-5 space-y-5">
        <div className="space-y-4">
          {metrics.map((metric, i) => {
            const valA = metric.keyA;
            const valB = metric.keyB;

            return (
              <div key={i} className="space-y-1.5">
                <div className="flex justify-between text-xs font-medium">
                  <span className="text-violet-300 font-bold">{valA.toFixed(1)}</span>
                  <span className="text-zinc-400">{metric.label}</span>
                  <span className="text-indigo-300 font-bold">{valB.toFixed(1)}</span>
                </div>

                {/* Dual Progress Bar */}
                <div className="grid grid-cols-2 gap-1.5 h-2 w-full">
                  {/* Film A (fills right-to-left) */}
                  <div className="h-full bg-zinc-900 rounded-l-full overflow-hidden flex justify-end">
                    <div
                      className="h-full bg-violet-500 rounded-l-full transition-all duration-500"
                      style={{ width: `${(valA / 10) * 100}%` }}
                    />
                  </div>
                  {/* Film B (fills left-to-right) */}
                  <div className="h-full bg-zinc-900 rounded-r-full overflow-hidden flex justify-start">
                    <div
                      className="h-full bg-indigo-500 rounded-r-full transition-all duration-500"
                      style={{ width: `${(valB / 10) * 100}%` }}
                    />
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        {/* Verdict Box */}
        <div className="p-4 rounded-xl bg-indigo-950/20 border border-indigo-500/20 space-y-2">
          <div className="flex items-center gap-1.5 text-[11px] font-bold uppercase tracking-wider text-indigo-400">
            <Trophy className="h-3.5 w-3.5" />
            Critical Verdict
          </div>
          <p className="text-xs text-zinc-300 leading-relaxed">{data.verdict}</p>
        </div>

        {/* Recommendations split */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-1">
          <div className="p-3 rounded-xl bg-zinc-900/50 border border-zinc-800 text-xs space-y-1">
            <span className="font-bold text-violet-400">Choose {data.filmA.title} if:</span>
            <p className="text-zinc-400 text-[11px] leading-relaxed">{data.recommendedFor.filmA}</p>
          </div>
          <div className="p-3 rounded-xl bg-zinc-900/50 border border-zinc-800 text-xs space-y-1">
            <span className="font-bold text-indigo-400">Choose {data.filmB.title} if:</span>
            <p className="text-zinc-400 text-[11px] leading-relaxed">{data.recommendedFor.filmB}</p>
          </div>
        </div>
      </div>
    </div>
  );
}
